### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by dream4r1** [dcoles/prometheus-pandas#6]
The url endpoint that I'm using has Basic Auth enabled how do I provide username and password using this query function ?. A sample code would be helpful

**Comment by dcoles** [comment]
Hi @dream4r1,

You can do this by passing in a [custom Requests `Session` object](https://docs.python-requests.org/en/latest/user/advanced/) with the `auth` property set:

```python
>>> import requests
>>> from prometheus_pandas import query
>>>
>>> http = requests.Session()
>>> http.auth = ('user', 'pass')  # Basic Authentication
>>>
>>> p = query.Prometheus('http://localhost:9090', http)
>>> print(p.query('node_cpu_seconds_total{mode="system"}', '2020-10-05T00:00:00Z'))
node_cpu_seconds_total{cpu="0",instance="localhost:9100",job="node",mode="system"}    3954.92
dtype: float64
```

I'll also add the example to the README. Hope that solves your issue.

**Comment by dream4r1** [comment]
Thank you.
